Feat rspy99/jupyterhub
RS-PYTHON/rs-infra-core pull request #14
Opened 2024-04-25 08:27 UTC by eroan-marie

2024-04-25 10:12 UTC, nleconte-csgroup requested changes
@eroan-marie some modifications are needed.

2024-04-25 10:12 UTC, nleconte-csgroup commented on apps/jupyterhub/values.yaml
> +      oauth_callback_url: https://staging1.{{ platform_domain_name }}/jupyter/hub/oauth_callback
Replace staging1 with processing or remove it.

2024-04-25 10:12 UTC, nleconte-csgroup commented on apps/keycloak/keycloakrealmimport.yaml
> +      rootUrl: https://staging1.{{ platform_domain_name }}
Replace staging1 with processing

2024-04-25 10:12 UTC, nleconte-csgroup commented on apps/keycloak/keycloakrealmimport.yaml
> +      adminUrl: https://staging1.{{ platform_domain_name }}
Replace staging1 with processing

2024-04-25 10:12 UTC, nleconte-csgroup commented on apps/keycloak/keycloakrealmimport.yaml
> +      - https://staging1.{{ platform_domain_name }}/*
Replace staging1 with processing

2024-04-25 10:12 UTC, nleconte-csgroup commented on apps/keycloak/keycloakrealmimport.yaml
> +      - https://staging1.{{ platform_domain_name }}
Replace staging1 with processing

2024-04-25 10:12 UTC, nleconte-csgroup commented on inventory/sample/group_vars/all/apps.yml
> +
There is a merge conflict here. Rebase first.

2024-04-26 13:10 UTC, eroan-marie commented on apps/jupyterhub/values.yaml
> +      oauth_callback_url: https://staging1.{{ platform_domain_name }}/jupyter/hub/oauth_callback
Done

2024-04-26 13:10 UTC, eroan-marie commented on inventory/sample/group_vars/all/apps.yml
> +
Rebase done

2024-04-29 12:32 UTC, nleconte-csgroup approved these changes

2024-04-29 12:32 UTC, merged