Feat rspy130/grafana
RS-PYTHON/rs-infra-core pull request #23
Opened 2024-05-13 08:39 UTC by eroan-marie

2024-05-13 13:09 UTC, nleconte-csgroup reviewed
@eroan-marie Could you have a look at my comments ?

2024-05-13 13:09 UTC, nleconte-csgroup commented on inventory/sample/group_vars/all/apps.yml
> +  custom_plugins: []
Could you describe in a documentation how to use that custom_plugins line ? For e.g. how can I edit it to use a plugin that was developed in phase1 ?
On phase1, we had to edit this file instead : https://github.com/COPRS/infrastructure/blob/main/inventory/sample/host_vars/setup/apps/grafana.yaml

2024-05-13 13:09 UTC, nleconte-csgroup commented on apps/grafana/podmonitor.yaml
Any reason to use PodMonitor instead of ServiceMonitor ?

2024-05-13 13:34 UTC, eroan-marie commented on inventory/sample/group_vars/all/apps.yml
> +  custom_plugins: []
Done

2024-05-13 13:34 UTC, eroan-marie commented on apps/grafana/podmonitor.yaml
Converted

2024-05-13 14:27 UTC, nleconte-csgroup requested changes
You must also add the header from now on every files, even the crds, e.g. : https://github.com/RS-PYTHON/rs-infrastructure/blob/08e063d177a8a30cb784f7af6a214b063db7246a/delete.yaml#L1-L13

2024-05-14 15:31 UTC, nleconte-csgroup approved these changes

2024-05-14 15:31 UTC, merged