Feat rspy335/dask gateway server
RS-PYTHON/rs-infra-core pull request #47
Opened 2024-07-22 07:59 UTC by clystard-csgroup

2024-07-22 13:25 UTC, nleconte-csgroup requested changes

2024-07-22 13:25 UTC, nleconte-csgroup commented on inventory/sample/host_vars/setup/apps.yml
> +  apiurl: http://hub.processing:8081/hub/api
Use the service url instead of the pod directly.

2024-07-22 13:25 UTC, nleconte-csgroup commented on inventory/sample/host_vars/setup/apps.yml
> +  apitoken: token
How is this token generated/extracted ?

2024-07-22 13:39 UTC, clystard-csgroup commented on inventory/sample/host_vars/setup/apps.yml
> +  apitoken: token
Replaced by "password generator command"

2024-07-22 14:01 UTC, nleconte-csgroup requested changes

2024-07-22 14:01 UTC, nleconte-csgroup commented on inventory/sample/host_vars/setup/apps.yml
> +  apitoken: "{{ lookup('password', '/dev/null', length=10, chars=['ascii_letters']) }}"
Almost there, can you increase `length` from 10 to 64 to follow the same as described in the doc here : https://gateway.dask.org/authentication.html#using-jupyterhub-s-authentication (`openssl rand -hex 32` generates a 64 characters long string).

2024-07-23 08:55 UTC, nleconte-csgroup requested changes

2024-07-23 08:55 UTC, nleconte-csgroup commented on apps/dask-gateway/values.yaml
> +      apiTokenFromSecretName: hub
It's either you provide directly the token value with `apiToken` or you provide the secret reference with `apiTokenFromSecretName` and  `apiTokenFromSecretKey` but not both.

The secret method is not recommended as the two component don't run in the same namespace : https://gateway.dask.org/install-kube.html#authenticating-with-jupyterhub

2024-08-01 07:51 UTC, nleconte-csgroup approved these changes

2024-08-02 12:59 UTC, merged