Feat rspy361/taints
RS-PYTHON/rs-infra-core pull request #77
Opened 2024-10-22 12:03 UTC by eroan-marie

2024-10-22 12:36 UTC, nleconte-csgroup requested changes

2024-10-22 12:36 UTC, nleconte-csgroup commented on inventory/sample/cluster.tfvars
> +buckets = ["test-ansible-collection"]
Are you sure about this one ?

2024-10-22 12:36 UTC, nleconte-csgroup commented on inventory/sample/cluster.tfvars
Could you also add the new node group in the template ?

2024-10-23 08:17 UTC, eroan-marie commented on inventory/sample/cluster.tfvars
> +buckets = ["test-ansible-collection"]
Oups, it was on the bottom of the file, I didn't see it. 
It's fixed :smile:

2024-10-23 08:17 UTC, eroan-marie commented on inventory/sample/cluster.tfvars
It's done

2024-10-24 13:54 UTC, nleconte-csgroup approved these changes

2024-10-24 13:54 UTC, merged